### ISSUE TITLE
Could the oligos example_data been used directly in Ribo-seq experiment?

### ISSUE THREAD

**Issue by gnilihzeux** [fallerlab/Ribo-ODDR#1]
Dear author,
    A little excited on your rRNA-deletion.
    It's a very big troubled problem that too many rRNA residue in ribo-seq.
   So, could the oligos in example_data been used directly in Ribo-seq experiment ?
  Or, they are just a part.
Wish your reply.

**Comment by ferhatalkan** [comment]
Thank you for your interest in our tool. 

Human oligos that are provided in the example_data are simply for testing the software. However, they have been taken from [this study](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2013-14-4-r32). At the end, they can of course be used for depletion but they may or may not perform well for your samples. 

Example_oligos are also for only software testing purposes. They have been designed using our own specific pilot data, therefore, we do not recommend them to be used for your specific experiments. 

Instead, we recommend you to run our software with your pilot Ribo-seq data and design optimal depletion oligos for your specific experiment. 

Best regards, Ferhat
