### ISSUE TITLE
Issue with execution of the Ribo-ODDR tool

### ISSUE THREAD

**Issue by sammywinchester19** [fallerlab/Ribo-ODDR#2]
I am trying to design rRNA depletion probes and I tried to use the example data with mouse_rRNA.fa as -r input and then placed the output in the current directory

it gives this error

Traceback (most recent call last):
  File "src/Ribo-ODDR.py", line 495, in <module>
    main()
  File "src/Ribo-ODDR.py", line 317, in main
    if len(args.samples)<1:
TypeError: object of type 'NoneType' has no len()

Can you please explain whats going on ?

**Comment by ferhatalkan** [comment]
Hi there. Seems like there is a problem with how you pass your input files to the pipeline. Can you share your full command so that I can help?

**Comment by sammywinchester19** [comment]
This is the command I placed in terminal

Ribo-ODDR-master/src/Ribo-ODDR.py -r DATA/Ribosomal_RNA -o /Results

**Comment by ferhatalkan** [comment]
Ribo-ODDR cannot design oligos without any pilot Ribo-seq data. It is made for designing oligos in an experiment-specific manner, with pilot data provided by the user for the specific experimental conditions. In your command line, you are not passing any pilot data to the pipeline, therefore it fails to execute. Please take a look at our README file to see how you can pass your pilot data to the pipeline.

**Comment by sammywinchester19** [comment]
Yes, thank you
